# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bf204c7abaa74c90c43aed88d61a0afb83f1d9a41b99898fca4433120aa7c103ee158c90760192a7ce37af86e8c868a6a54abb12e23c7c3b92a137629331196

test:
  secret_key_base: 86c7ff4168a1d8ad7565c0feff14b9942476e76350e4974096437d1c3a4cf7a85e0ae01db31d3d8522af2374c2c803fb3c4b22a955a66f250795e46065cdca2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
